fix: husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,21 +1,1 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
-# 定义一个函数来输出带颜色的文本
-# 第一个参数是颜色代码，第二个参数是要输出的文本
-print_colored() {
-  local color_code="$1"
-  local text="$2"
-  echo -e "\033[${color_code}m${text}\033[0m"
-}
-
-# 运行 lint
-npm run lint
-
-# 检查 lint 的退出状态
-if [ $? -eq 0 ]; then
-  print_colored 32 "Linting successful"  # 32 是绿色的 ANSI 代码
-else
-  print_colored 31 "Linting failed!"     # 31 是红色的 ANSI 代码
-  exit 1
-fi
+#!/usr/bin/env sh. "$(dirname -- "$0")/_/husky.sh"# 定义一个函数来输出带颜色的文本# 第一个参数是颜色代码，第二个参数是要输出的文本print_colored() {  color_code="$1"  text="$2"  printf "\033[${color_code}m%s\033[0m\n" "$text"}# 运行 lint 并直接检查其退出状态if npm run lint; then  print_colored 32 "Linting successful" # 32 是绿色的 ANSI 代码else  print_colored 31 "Linting failed!" # 31 是红色的 ANSI 代码  exit 1fi
